config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    sessions: 'clients/sessions',
    registrations: 'clients/registrations'
  }
  root 'products#marketplace'

  get 'carts/show' => 'carts#show'
  post 'carts/checkout' => 'carts#checkout'
  get 'carts/add_product/:slug' => 'carts#add_product', as: :add_to_cart
  get 'carts/remove_product/:id' => 'carts#remove_product', as: :remove_from_cart
  get 'carts/apply_cupon' => 'carts#apply_cupon'

  post 'webhooks/moip' => 'webhooks#moip'

  get 'marketplace' => 'products#marketplace'
  get 'products/:slug' => 'products#show', as: :product
end

app/views/shared/_cart_product.html.erb
<li class='cart-item-<%= cart_item.id %>'>
  <div class="col-xs-4 thumb-image-wrapper">
    <%= image_tag cart_item.product.image_name,
    alt: '', id: 'thumb-image' %>
  </div>
  <div class="col-xs-8">
    <%= link_to remove_from_cart_path(id: cart_item.id, format: 'js'),
                                 class: 'close', remote: true do %>
          <span class="fa fa-times"></span>
          <span class="sr-only">Deletar</span>
    <% end %>
    <div class="overflow-h">
      <span><%= cart_item.product.title %></span>
      <small>
        <span id="quantity-product-<%= cart_item.id %>"><%= cart_item.quantity %></span> x <%= number_to_currency(cart_item.product.value, unit: 'R$', separator: ',', delimiter: '.') %></small>
      </div>
  </div>
</li>

app/views/shared/_footer.html.erb
<!--=== Footer v4 ===-->
<div class="footer-v4">
  <div class="footer">
    <div class="container">
      <div class="row">
        <!-- About -->
        <div class="col-md-12 md-margin-bottom-40">
          <%= link_to root_path, id: 'logo-footer-wrapper' do %>
            <%= image_tag 'logo.png', id: 'logo-footer' %>
          <% end %>
          <p class="text-center">Loja de instrumentos musicais para teste da moip.</p>
        </div>
        <!-- End About -->
      </div><!--/end row-->
    </div><!--/end continer-->
  </div><!--/footer-->

  <div class="copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>
            2017 &copy; Marcelo Mita. ALL Rights Reserved.
          </p>
        </div>
      </div>
    </div>
  </div><!--/copyright-->
</div>

app/views/shared/_header.html.erb
<!--=== Header v5 ===-->
<div class="header-v5 header-static">
  <!-- Navbar -->
  <div class="navbar navbar-default mega-menu" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', alt: 'Logo', id: 'logo-header' %>
        <% end %>
      </div>

      <!-- Shopping Cart -->
      <div class="shop-badge badge-icons pull-right">
        <a href="#" data-turbolinks="false"><i class="fa fa-shopping-cart"></i></a>
        <span class="badge badge-sea rounded-x"
              id='cart-quantity'>
              <%= @cart.quantity %>
        </span>
        <div class="badge-open">
          <ul class="list-unstyled mCustomScrollbar"
              data-mcs-theme="minimal-dark"
              id="cart-list">
            <% @cart.cart_items.each do |cart_item| %>
              <%= render partial: 'shared/cart_product', locals: { cart_item: cart_item } %>
            <% end %>
          </ul>
          <div class="subtotal">
            <div class="overflow-h margin-bottom-10">
              <span>Subtotal</span>
              <span class="pull-right subtotal-cost">
                <%= number_to_currency(@cart.calculate_subtotal_value, unit: 'R$', separator: ',', delimiter: '.') %>
              </span>
            </div>
            <div class="row">
              <div class="col-xs-6">
                <a href="#" class="btn-u btn-brd btn-brd-hover btn-u-sea-shop btn-block">View Cart</a>
              </div>
              <div class="col-xs-6">
                <%= link_to 'Finalizar compra', carts_show_path,
                            class: "btn-u btn-u-sea-shop btn-block" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- End Shopping Cart -->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-responsive-collapse">
        <!-- Nav Menu -->
        <ul class="nav navbar-nav">
          <!-- Pages -->
          <!-- <li class="dropdown active">
            <a href="javascript:void(0);" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown">
              Pages
            </a>
            <ul class="dropdown-menu">
              <li class="active"><a href="index.html">Shop UI</a></li>
              <li><a href="shop-ui-inner.html">Product Page</a></li>
              <li><a href="shop-ui-filter-grid.html">Filter Grid Page</a></li>
              <li><a href="shop-ui-filter-list.html">Filter List Page</a></li>
              <li><a href="shop-ui-add-to-cart.html">Checkout</a></li>
              <li><a href="shop-ui-login.html">Login</a></li>
              <li><a href="shop-ui-register.html">Register</a></li>
            </ul>
          </li> -->
          <!-- End Pages -->
        </ul>
        <!-- End Nav Menu -->
      </div>
    </div>
  </div>
  <!-- End Navbar -->
</div>
<!--=== End Header v5 ===-->

app/views/shared/_product_card.html.erb
<div class="item col-md-3">
  <div class="product-img">
    <%= image_tag product.image_name, alt: '', class: 'full-width img-responsive' %>
    <%= link_to add_to_cart_path(slug: product.cached_slug, format: 'js'),
                class: 'add-to-cart',
                remote: true do %>
      <i class="fa fa-shopping-cart"></i>Adicionar ao Carrinho
    <% end %>
  </div>
  <div class="product-description product-description-brd">
    <div class="overflow-h margin-bottom-5">
      <div>
        <h4 class="title-price">
          <%= product.title %>
        </h4>
        <span class="gender"><%= product.description %></span>
      </div>
      <div class="product-price">
        <span class="title-price">
          R$ <%= product.value.to_s.gsub('.', ',') %>
        </span>
      </div>
    </div>
  </div>
</div>